### ISSUE TITLE
Violations appears on deleted assets

### ISSUE THREAD

**Issue by MarcFundenberger** [BrunoReboul/terraform-google-realtime-asset-monitor#23]
In some cases, deletion messages from CAI are analysed BEFORE other messages on the same asset, resulting in the evaluationTimestamp being posterior to the one from the deletion message. 
This results in the last_compliancestatus for that asset/rule having non compliant assets even even when deleted.

Please find a proposed fix for the view last_compliancestatus.

[last_compliancestatus.txt](https://github.com/BrunoReboul/terraform-google-realtime-asset-monitor/files/8621737/last_compliancestatus.txt)

NB. : I also included a fix (to be tweaked) for the related case of having IAM messages over 2 days after a resource deletion message.

**Comment by BrunoReboul** [comment]
Thanks for the issue and the solution Marc !!
Closed with PR #24
